name: Build

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:5.6

    steps:
      - uses: actions/checkout@v2

      - name: Swift Build
        run: swift build