name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/swift:latest

    steps:
      - uses: actions/checkout@v2

      - name: Swift Build
        run: swift build -c release --triple wasm32-unknown-wasi

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@main

      - name: Package for Compute@Edge
        run: fastly compute pack --wasm-binary ./.build/release/HelloCompute.wasm

      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions/deploy@main
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}